// <auto-generated />
using System;
using DA_Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DA_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DA_Web.Models.BangVeModule.BanVe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhThuNhoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("CongKhai")
                        .HasColumnType("bit");

                    b.Property<string>("DuLieuCanvasJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("BanVes");
                });

            modelBuilder.Entity("DA_Web.Models.BangVeModule.NguoiVeChung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BanVeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BanVeId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NguoiVeChungs");
                });

            modelBuilder.Entity("DA_Web.Models.BangVeModule.TaiNguyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiTaiNguyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTaiNguyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TaiNguyens");
                });

            modelBuilder.Entity("DA_Web.Models.GiaoDucModule.BaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhThuNhoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ChuDeId")
                        .HasColumnType("int");

                    b.Property<int>("DiemThuong")
                        .HasColumnType("int");

                    b.Property<string>("DoKho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChuDeId");

                    b.ToTable("BaiHocs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnhThuNhoUrl = "/assets/lessons/meocon.png",
                            ChuDeId = 2,
                            DiemThuong = 20,
                            DoKho = "De",
                            MoTa = "Học vẽ từng bước chú mèo dễ thương đang ngồi chơi.",
                            NgayTao = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TieuDe = "Vẽ chú mèo con"
                        },
                        new
                        {
                            Id = 2,
                            AnhThuNhoUrl = "/assets/lessons/matanime.png",
                            ChuDeId = 1,
                            DiemThuong = 30,
                            DoKho = "TrungBinh",
                            MoTa = "Từng bước phác thảo và vẽ chi tiết mắt lấp lánh kiểu Anime.",
                            NgayTao = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TieuDe = "Vẽ mắt Anime nữ"
                        },
                        new
                        {
                            Id = 3,
                            AnhThuNhoUrl = "/assets/lessons/donut.png",
                            ChuDeId = 3,
                            DiemThuong = 15,
                            DoKho = "De",
                            MoTa = "Vẽ chiếc bánh vòng donut phủ kem dâu ngọt ngào.",
                            NgayTao = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TieuDe = "Vẽ chiếc bánh Donut"
                        });
                });

            modelBuilder.Entity("DA_Web.Models.GiaoDucModule.CacBuocBaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<string>("ChuKyHuongDan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DuLieuGuideSvg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LaBuocToMau")
                        .HasColumnType("bit");

                    b.Property<int>("SoThuTuBuoc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.ToTable("CacBuocBaiHocs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaiHocId = 1,
                            ChuKyHuongDan = "Bước 1: Hãy vẽ một hình tròn to để làm đầu của chú mèo nhé!",
                            DuLieuGuideSvg = "M 100 100 A 50 50 0 1 1 99.9 100",
                            LaBuocToMau = false,
                            SoThuTuBuoc = 1
                        },
                        new
                        {
                            Id = 2,
                            BaiHocId = 1,
                            ChuKyHuongDan = "Bước 2: Vẽ thêm hai hình tam giác nhọn ở phía trên để làm đôi tai xinh.",
                            DuLieuGuideSvg = "M 120 53 L 130 20 L 150 43 M 80 53 L 70 20 L 50 43",
                            LaBuocToMau = false,
                            SoThuTuBuoc = 2
                        },
                        new
                        {
                            Id = 3,
                            BaiHocId = 1,
                            ChuKyHuongDan = "Bước 3: Vẽ thêm hai hình tròn nhỏ xíu bên trong làm đôi mắt long lanh và cái miệng cười.",
                            DuLieuGuideSvg = "M 85 90 A 5 5 0 1 1 84.9 90 M 115 90 A 5 5 0 1 1 114.9 90 M 100 105 Q 100 115 105 105 Q 100 115 95 105",
                            LaBuocToMau = false,
                            SoThuTuBuoc = 3
                        },
                        new
                        {
                            Id = 4,
                            BaiHocId = 1,
                            ChuKyHuongDan = "Bước 4: Cuối cùng, hãy chọn màu và tô điểm cho chú mèo của bạn thật rực rỡ!",
                            DuLieuGuideSvg = "",
                            LaBuocToMau = true,
                            SoThuTuBuoc = 4
                        });
                });

            modelBuilder.Entity("DA_Web.Models.GiaoDucModule.ChuDe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDienUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenChuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ChuDes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnhDaiDienUrl = "/assets/topics/anime.png",
                            MoTa = "Học vẽ nhân vật truyện tranh, mắt Anime lung linh và các phụ kiện dễ thương.",
                            TenChuDe = "Anime"
                        },
                        new
                        {
                            Id = 2,
                            AnhDaiDienUrl = "/assets/topics/dongvat.png",
                            MoTa = "Tập vẽ các con vật gần gũi như con mèo, chú chó, chú khỉ ngộ nghĩnh.",
                            TenChuDe = "Động vật"
                        },
                        new
                        {
                            Id = 3,
                            AnhDaiDienUrl = "/assets/topics/doan.png",
                            MoTa = "Tập vẽ các món ăn bé thích như hamburger, kem ly, bánh ngọt.",
                            TenChuDe = "Đồ ăn"
                        },
                        new
                        {
                            Id = 4,
                            AnhDaiDienUrl = "/assets/topics/cayco.png",
                            MoTa = "Học vẽ các loài hoa xinh đẹp, cây thông Noel hay hoa hướng dương.",
                            TenChuDe = "Cây cỏ"
                        });
                });

            modelBuilder.Entity("DA_Web.Models.GiaoDucModule.HuyHieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HinhAnhUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("HuyHieus");
                });

            modelBuilder.Entity("DA_Web.Models.GiaoDucModule.HuyHieuNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HuyHieuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HuyHieuId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("HuyHieuNguoiDungs");
                });

            modelBuilder.Entity("DA_Web.Models.GiaoDucModule.TienTrinhNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhVeNguoiDungUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<int>("BuocCaoNhatDatDuoc")
                        .HasColumnType("int");

                    b.Property<int?>("DiemAiCham")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NhanXetAi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("TienTrinhNguoiDungs");
                });

            modelBuilder.Entity("DA_Web.Models.NguoiDungModule.BangXepHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiemDatDuoc")
                        .HasColumnType("int");

                    b.Property<string>("LoaiXepHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("BangXepHangs");
                });

            modelBuilder.Entity("DA_Web.Models.NguoiDungModule.KetBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId1")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId2")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId1");

                    b.HasIndex("NguoiDungId2");

                    b.ToTable("KetBans");
                });

            modelBuilder.Entity("DA_Web.Models.NguoiDungModule.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDienUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CapDoHienTai")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenHienThi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TongDiem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("DA_Web.Models.PhongChoModule.NguoiChoiTrongPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("PhongChoId")
                        .HasColumnType("int");

                    b.Property<bool>("SanSang")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("PhongChoId");

                    b.ToTable("NguoiChoiTrongPhongs");
                });

            modelBuilder.Entity("DA_Web.Models.PhongChoModule.PhongCho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuPhongId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChuPhongId");

                    b.ToTable("PhongChos");
                });

            modelBuilder.Entity("DA_Web.Models.TroChoiModule.LuotChoiGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiemDatDuoc")
                        .HasColumnType("int");

                    b.Property<string>("DuLieuNoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiLuotChoi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("LuotTruocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiChoiId")
                        .HasColumnType("int");

                    b.Property<int>("VongChoiGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LuotTruocId");

                    b.HasIndex("NguoiChoiId");

                    b.HasIndex("VongChoiGameId");

                    b.ToTable("LuotChoiGames");
                });

            modelBuilder.Entity("DA_Web.Models.TroChoiModule.PhienChoiGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongChoId")
                        .HasColumnType("int");

                    b.Property<int>("TongSoVong")
                        .HasColumnType("int");

                    b.Property<int>("VongHienTai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhongChoId");

                    b.ToTable("PhienChoiGames");
                });

            modelBuilder.Entity("DA_Web.Models.TroChoiModule.VongChoiGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PhienChoiGameId")
                        .HasColumnType("int");

                    b.Property<int>("SoThuTuVong")
                        .HasColumnType("int");

                    b.Property<string>("TuKhoaGoc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PhienChoiGameId");

                    b.ToTable("VongChoiGames");
                });

            modelBuilder.Entity("DA_Web.Models.BangVeModule.BanVe", b =>
                {
                    b.HasOne("DA_Web.Models.NguoiDungModule.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DA_Web.Models.BangVeModule.NguoiVeChung", b =>
                {
                    b.HasOne("DA_Web.Models.BangVeModule.BanVe", "BanVe")
                        .WithMany()
                        .HasForeignKey("BanVeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DA_Web.Models.NguoiDungModule.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BanVe");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DA_Web.Models.GiaoDucModule.BaiHoc", b =>
                {
                    b.HasOne("DA_Web.Models.GiaoDucModule.ChuDe", "ChuDe")
                        .WithMany()
                        .HasForeignKey("ChuDeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuDe");
                });

            modelBuilder.Entity("DA_Web.Models.GiaoDucModule.CacBuocBaiHoc", b =>
                {
                    b.HasOne("DA_Web.Models.GiaoDucModule.BaiHoc", "BaiHoc")
                        .WithMany()
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHoc");
                });

            modelBuilder.Entity("DA_Web.Models.GiaoDucModule.HuyHieuNguoiDung", b =>
                {
                    b.HasOne("DA_Web.Models.GiaoDucModule.HuyHieu", "HuyHieu")
                        .WithMany()
                        .HasForeignKey("HuyHieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DA_Web.Models.NguoiDungModule.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HuyHieu");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DA_Web.Models.GiaoDucModule.TienTrinhNguoiDung", b =>
                {
                    b.HasOne("DA_Web.Models.GiaoDucModule.BaiHoc", "BaiHoc")
                        .WithMany()
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DA_Web.Models.NguoiDungModule.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DA_Web.Models.NguoiDungModule.BangXepHang", b =>
                {
                    b.HasOne("DA_Web.Models.NguoiDungModule.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DA_Web.Models.NguoiDungModule.KetBan", b =>
                {
                    b.HasOne("DA_Web.Models.NguoiDungModule.NguoiDung", "NguoiDung1")
                        .WithMany()
                        .HasForeignKey("NguoiDungId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA_Web.Models.NguoiDungModule.NguoiDung", "NguoiDung2")
                        .WithMany()
                        .HasForeignKey("NguoiDungId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung1");

                    b.Navigation("NguoiDung2");
                });

            modelBuilder.Entity("DA_Web.Models.PhongChoModule.NguoiChoiTrongPhong", b =>
                {
                    b.HasOne("DA_Web.Models.NguoiDungModule.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA_Web.Models.PhongChoModule.PhongCho", "PhongCho")
                        .WithMany()
                        .HasForeignKey("PhongChoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("PhongCho");
                });

            modelBuilder.Entity("DA_Web.Models.PhongChoModule.PhongCho", b =>
                {
                    b.HasOne("DA_Web.Models.NguoiDungModule.NguoiDung", "ChuPhong")
                        .WithMany()
                        .HasForeignKey("ChuPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuPhong");
                });

            modelBuilder.Entity("DA_Web.Models.TroChoiModule.LuotChoiGame", b =>
                {
                    b.HasOne("DA_Web.Models.TroChoiModule.LuotChoiGame", "LuotTruoc")
                        .WithMany()
                        .HasForeignKey("LuotTruocId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DA_Web.Models.NguoiDungModule.NguoiDung", "NguoiChoi")
                        .WithMany()
                        .HasForeignKey("NguoiChoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DA_Web.Models.TroChoiModule.VongChoiGame", "VongChoiGame")
                        .WithMany()
                        .HasForeignKey("VongChoiGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LuotTruoc");

                    b.Navigation("NguoiChoi");

                    b.Navigation("VongChoiGame");
                });

            modelBuilder.Entity("DA_Web.Models.TroChoiModule.PhienChoiGame", b =>
                {
                    b.HasOne("DA_Web.Models.PhongChoModule.PhongCho", "PhongCho")
                        .WithMany()
                        .HasForeignKey("PhongChoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongCho");
                });

            modelBuilder.Entity("DA_Web.Models.TroChoiModule.VongChoiGame", b =>
                {
                    b.HasOne("DA_Web.Models.TroChoiModule.PhienChoiGame", "PhienChoiGame")
                        .WithMany()
                        .HasForeignKey("PhienChoiGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhienChoiGame");
                });
#pragma warning restore 612, 618
        }
    }
}
